[build]
  functions = "dist/lambda"
  command = "yarn build"
[context.production.environment]
  TOML_ENV_VAR = "From netlify.toml"
  REACT_APP_TOML_ENV_VAR = "From netlify.toml (REACT_APP_)"
  REACT_APP_TOML_ENV = "From netlify.t"
